### ISSUE TITLE
carve_chunk_to_file use sendfile instead of a read/wrtite loop

### ISSUE THREAD

**Issue by martonilles** [IoT-Inspector/unblob#275]
read write loop is slow and resource intensive, we could use os.sendfile

low-prio

**Comment by e3krisztian** [comment]
On the first attempt at implementing it, it turned out, that while `os.sendfile` requires file objects to work, we not necessarily have files (e.g. in tests, or potentially from web requests).

Looking at the potential performance improvements (no measurements made, depending on [others](https://bugs.python.org/issue33639)), and unforeseen failures (at least a [similar implementation](https://github.com/python/cpython/pull/7100/files#diff-db8ac59326160713929e0e1973aef54f0280fe9f154ef24d14244909a0e0689bR90) hints at limits in copied chunks, as well as this [bug discussion](https://trac.nginx.org/nginx/ticket/1870)), this optimization is probably not worth implementing - at least until we are 100% sure we need it.

**Comment by e3krisztian** [comment]
Another idea was to use `shutil.copyfileobj`, which internally uses the optimization, and has a `length` parameter, but it does not support stopping after certain length, the parameter is the size of the buffer.

Closing as agreed in person.
