### ISSUE TITLE
Return different exit codes based on received reports

### ISSUE THREAD

**Issue by QKaiser** [IoT-Inspector/unblob#299]
unblob currently returns 0 if it does not receive any reports, and 1 otherwise.

Reports include:

* **MaliciousSymlinkRemoved** - an error when malicious symlinks have been removed from disk
* **ExtractorDependencyNotFoundReport** - an error when the dependency of an extractor doesn't exist
* **ExtractCommandFailedReport** - an error when failed to run the extraction command
* **UnknownError** - an exception raised during file processing
* **CalculateChunkExceptionReport** - an exception raised during calculate_chunk execution

This represents a large array of exception and we should agree first on a list of exceptions that we are willing to accept. To me, we must accept the following exceptions:

* **MaliciousSymlinkRemoved** - it will happen all the time and is not a problem in itself
* **ExtractCommandFailedReport** - it will happen all the time on weird misidentified chunks is not a problem in itself

And we must stop if we encounter those:

* **ExtractorDependencyNotFoundReport** - things will obviously go wrong down the line
* **UnknownError** - something bad happened and we should know about it
* **CalculateChunkExceptionReport** - something bad happened and we should know about it

In the case of a vendor firmware, the processing stopped because unblob returned an exit code of '1' because it couldn't extract an ARJ archive false positive.

I'd recommend assigning an exit code to each Report class, with increasing values:

1. MaliciousSymlinkRemoved
1. ExtractCommandFailedReport
1. CalculateChunkExceptionReport
1. UnknownError
1. ExtractorDependencyNotFoundReport

The exit code values do not need to be different for each report, we could also do something like:

```python
class ReturnCode(Enum):
  OK: 0
  STILL_WORKING: 1
  REAL_BAD: 2
  CANNOT_EVEN_RUN: 3
```

And assign an enum value to our report classes, so that we can add new report types later on if needed.

**Comment by QKaiser** [comment]
Márton comment:

> Agree with Quentin, we need to distinguish between fatal errors where we need to stop processing and just some non-complete errors. Though we should probably need to notify the user if non-fatal error occurred.

> I would also look at ExtractCommandFailedReport as that is a false-positive from the handler. We should try to minimize these occurrences.

> Personally I think unblob should somehow signal in the exit code like the Enum suggestion as we have the most context there. Probably we should include these error reports in the metadata as well.

**Comment by vlaci** [comment]
Some design guidelines (sorry for not replying sooner):

- Reserve  `1` for critical and otherwise unexpected and unhandled errors: e.g. a `SyntaxError` will cause python exit with `1`. There are a few cases like this that causes abnormal program termination that we have no control over (Just for completeness I have to mention that we could introduce a `sys.excepthook` but would it be a good idea?)
- Many command line applications and `python` itself returns with `2` for usage errors. That's no rule but a nice convention
- (not a requirement but a fact): The program will exit with 8 bits 2's complement encoding of the signal which causes it to crash, so that e.g. an issue in yara's C binding most probably will cause it to exit with `-11`
