### ISSUE TITLE
Write Dockerfile

### ISSUE THREAD

**Issue by kissgyorgy** [IoT-Inspector/unblob#36]
A simple Dockerfile which has all required external dependencies installed.

**Comment by kukovecz** [comment]
Also, I think we need to refactor the gitub actions to build a container based on the Dockerfile and run the checks / tests inside that container.

The problem is, both the `tests` and `checks` github actions are doing a `Install 3rd party from apt` step. It would be easier to build a container and run everything from it.

The messy thing is, the `checks` sometimes does not need every package....
For example as I was checking this merge request: https://github.com/IoT-Inspector/unblob/pull/89/files
I just saw that it introduced a new dependency (lzop package) and this branch adds it to the `tests` github action, but it does not add it to the `checks`, and the checks can be executed.
